version: '3'
services:
  zk-dubbo-admin:
    image: zerechen/zookeeper-dubbo:1.0
    ports:
      - "2181:2181"
      - "10000:8080"

  czl-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: --appendonly yes
    volumes:
      - ./redis_data:/data