version: '3'
services:
  zk-dubbo-admin:
    image: zerechen/zookeeper-dubbo:1.0
    ports:
      - "2181:2181"
      - "10000:8080"

  czl-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: --appendonly yes
    volumes:
      - ./redis_data:/data

  czl-controller:
    build: Czl-Controller/
    ports:
      - "8081:8080"
    volumes:
      - ./logs/controller:/logs/
    depends_on:
      - czl-redis
      - zk-dubbo-admin
      - czl-product
      - czl-user

  czl-user:
    build: Czl-User/
    ports:
      - "8082:8080"
    volumes:
      - ./logs/user:/logs/
    depends_on:
      - zk-dubbo-admin

  czl-product:
    build: Czl-Product/
    ports:
      - "8083:8080"
    volumes:
      - ./logs/product:/logs/
    depends_on:
      - zk-dubbo-admin

  czl-ui:
    build: Czl-UI-Frontend
    ports:
      - "8080:8080"