version: '2.0'
services:
  zk-dubbo-admin:
    image: zerechen/zookeeper-dubbo:1.0
    container_name: czl-zk-dubbo-admin
    ports:
      - "2181:2181"
      - "10000:8080"

  czl-redis:
    image: redis
    container_name: czl-redis
    ports:
      - "6379:6379"
    restart: always
    command: --appendonly yes
    volumes:
      - ./redis_data:/data

  czl-controller:
    build: Czl-Controller/
    container_name: czl-controller
    ports:
      - "8002:8000"
    volumes:
      - ./logs/controller:/logs/

  czl-user:
    build: Czl-User/
    container_name: czl-user
    ports:
      - "8003:8000"
    volumes:
      - ./logs/user:/logs/